apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "syncthing-relaysrv.fullname" . }}
  labels:
    {{- include "syncthing-relaysrv.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "syncthing-relaysrv.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "syncthing-relaysrv.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "syncthing-relaysrv.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["-keys=/var/strelaysrv", "-pools=", "-status-srv=0.0.0.0:22000", "-network-timeout={{ .Values.relay.networkTimeout }}", "-ping-interval={{ .Values.relay.pingInterval }}", "-debug", "-listen=0.0.0.0:22067"]
          ports:
            - name: listen
              containerPort: 22067
              protocol: TCP
            - name: status
              containerPort: 22000
              protocol: TCP
          volumeMounts:
            - name: relaysrv-data
              mountPath: /var/strelaysrv
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: relaysrv-data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "syncthing-relaysrv.fullname" . }}
          {{- else }}
          emptyDir: {}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
