apiVersion: v1
kind: Service
metadata:
  name: {{ include "syncthing-relaysrv.fullname" . }}
  labels:
    {{- include "syncthing-relaysrv.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: listen
      protocol: TCP
      name: listen
  selector:
    {{- include "syncthing-relaysrv.selectorLabels" . | nindent 4 }}
